Declare a variable and assign it a string value. Then print that string following this rule: only the letters c o d e r should be included in your output if they are present in the word. Otherwise, exclude that specific letter. An example would be: 'condition' would be printed as 'codo'.	40pts	Paste Python, Javascript, or Java solution and submit
8	Declare a variable and assign it to a string. The code should print ”Yes” if all the words in the string begin with an uppercase letter. print ”No” otherwise. You cannot use a library for this solution.	40pts	Paste Python, Javascript, or Java solution and submit
9	Declare a variable and assign it to a list of integers. Calculate and print ”Yes” if the list has any duplicates, otherwise print ”No”. You cannot use a library for this solution.	50pts	Paste Python, Javascript, or Java solution and submit
10	Declare a variable and assign it to a non-empty string. Then construct a string that is formatted this way: ”Coder” becomes ”CoderCodeCodCoC”. Print the newly formatted string. You must use string splicing.	50pts	Paste Python, Javascript, or Java solution and submit
11	Declare a variable and assign it a string containing the characters ”x” and ”o”. Then calculate and print ”Yes” or ”No” depending on whether they have the same number of x's and o's.	50pts	Paste Python, Javascript, or Java solution and submit
12	Declare a variable and assign it to a string. Print that string with an added space in between all of the letters. If there's a space in the string, you should not consider it a letter and not add an extra space.	60pts	Paste Python, Javascript, or Java solution and submit
13	Declare a variable and assign a string to it. The string should contain at least one capital letter. Print the string, moving all the capital letters to the front (leftmost position).	70pts	Paste Python, Javascript, or Java solution and submit
14	Declare a variable and assign it to an integer between 0-255. Convert it to its octal equivalent with an algorithm. You cannot use a library for this solution.	80pts	Paste Python, Javascript, or Java solution and submit
15	Declare two variables and assign them to strings. Print the number of the positions where they contain the same length 3 substring. So 'xxzaazz' and 'xxzaaz' yields 4, since the 'xxz', 'xza', 'zaa', and 'aaz' substrings appear in the same place in both strings. You cannot use a library for this solution.	80pts	Paste Python, Javascript, or Java solution and submit
16	Declare a variable and assign it to a string. Write a regular expression to check that a string contains only a certain set of characters: a-z, A-Z and 0-9. If it does, print ”Yes”, otherwise print ”No”. You can use the ”re” module to solve.	90pts	Paste Python, Javascript, or Java solution and submit
17	Implement radix sort and call it on a list of 10 numbers, sorting from smallest to largest. You cannot use a library for this solution.